import { chromium } from "/root/hermes-agent/node_modules/playwright/index.mjs";
import { mkdir, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
import sharp from "sharp";

const out = "/tmp/grandmajazz-rack-qa";
await mkdir(out, { recursive: true });
const base = "http://127.0.0.1:3024";
const original = await (await fetch(`${base}/api/garments/issues`)).json();
assert(original.issues.length, "Run upload QA first to prepare isolated artwork");
const issues = Array.from({ length: 24 }, (_, i) => ({ ...original.issues[0], id: `rack-qa-${i + 1}`, slug: `rack-qa-${i + 1}`, title: `Development edition ${i + 1}`, issueNumber: String(i + 1) }));
const browser = await chromium.launch({ executablePath: "/root/.cache/ms-playwright/chromium_headless_shell-1217/chrome-headless-shell-linux64/chrome-headless-shell", args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; page.on("pageerror", e => errors.push(e.message));
await page.route("**/api/garments/issues", route => route.fulfill({ json: { logo: null, issues } }));
const mode = value => page.waitForFunction(value => document.querySelector("[data-mode]")?.dataset.mode === value, value, { timeout: 60000 });
try {
  await page.goto(`${base}/garments`); await mode("browsing");
  await page.waitForFunction(() => document.querySelector("[data-mode]")?.dataset.coversLoaded === "12", null, { timeout: 60000 });
  assert.equal(await page.locator("[data-issue]").count(), 12);
  await page.screenshot({ path: `${out}/desktop-twelve-editions.png`, fullPage: true });
  const pixels = await sharp(await page.locator("canvas").screenshot()).stats();
  assert(pixels.channels[0].stdev > 20);
  await page.getByRole("button", { name: "Next rack bay" }).click(); await page.getByText("13-24 of 24 editions", { exact: true }).waitFor();
  await page.locator('[data-issue="rack-qa-14"]').click(); await mode("reading");
  await page.getByRole("button", { name: "Next page", exact: true }).click(); await mode("reading");
  const position = await page.locator("[data-mode]").getAttribute("data-page");
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(1000);
  assert.equal(await page.locator("[data-mode]").getAttribute("data-page"), position);
  assert.equal(await page.locator("[data-mode]").getAttribute("data-mode"), "reading");
  await page.getByRole("button", { name: "Return to newsstand", exact: true }).click(); await mode("browsing");
  await page.waitForTimeout(1000);
  assert.equal(await page.locator("[data-issue]").count(), 6);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.waitForFunction(() => document.querySelector("[data-mode]")?.dataset.coversLoaded === "6", null, { timeout: 60000 });
  await page.screenshot({ path: `${out}/mobile-six-editions.png`, fullPage: true });
  await page.getByRole("button", { name: "Next rack bay" }).click();
  await page.getByText("19-24 of 24 editions", { exact: true }).waitFor();
  await page.goto(`${base}/garments/rack-qa-24`); await mode("reading");
  assert((await page.url()).endsWith("rack-qa-24"));
  await page.getByRole("button", { name: "Return to newsstand", exact: true }).click(); await mode("browsing");
  await page.getByText("19-24 of 24 editions", { exact: true }).waitFor();
  assert(await page.getByRole("button", { name: "Next rack bay" }).isDisabled());
  await page.locator("[data-mode]").evaluate(el => el.dispatchEvent(new Event("garments:metrics")));
  const metrics = JSON.parse(await page.locator("[data-mode]").getAttribute("data-metrics"));
  assert(metrics.textures <= 18, `Unexpected GPU texture count: ${metrics.textures}`);
  assert.deepEqual(errors, []);
  await writeFile(`${out}/result.json`, JSON.stringify({ editions: 24, desktopVisible: 12, mobileVisible: 6, resizePreservesPage: true, lastIssueDeepLink: true, pixels: pixels.channels.map(c => c.stdev), metrics, errors }, null, 2));
  console.log("24-edition rack, twelve desktop / six mobile, bay navigation, reading resize, deep links, GPU bounds: PASS");
} finally { await browser.close(); }
